[package]
name = "fdm_cost_calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
image = "0.25.5"
windows = { version = "0.58.0", features = ["Win32_UI_WindowsAndMessaging"] }
egui_extras = "0.29.1"
